name: Build Design Tokens

on:
  push:
    branches:
      - design/token
    paths:
      - "styles/Tokens.json"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Style Dictionary Build
        run: npm run token-build

      - name: Commit and push built tokens
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add styles/tokens/light.css styles/tokens/dark.css
          git commit -m "style: design token으로 css variables 업데이트" || echo "No changes to commit"
          git push origin HEAD
